### ISSUE TITLE
cannot connect the port,what is the problem?

### ISSUE THREAD

**Issue by msean** [ErDmKo/asyncmc#6]
I used  the example code to hava a test,but happend an error below this:
```
Traceback (most recent call last):
  File "/home/mwh/ad_tornado/asyncmc_test.py", line 17, in <module>
    loop.run_sync(out)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mwh/ad_tornado/asyncmc_test.py", line 10, in out
    yield mc.set(b"some_key", b"Some value")
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/asyncmc/client.py", line 63, in wrapper
    res = yield func(self, conn, *args, **kwargs)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/asyncmc/client.py", line 261, in set
    conn, b'set', self._key_type(key=key), value, exptime, noreply)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/asyncmc/client.py", line 517, in _storage_command
    resp = yield server.send_cmd(cmd, noreply=noreply)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/home/mwh/virtualenv_mwh/lib/python3.4/site-packages/asyncmc/host.py", line 89, in send_cmd
    self.disconect_reason
asyncmc.exceptions.ConnectionDeadError: socket host "localhost" port "11211" disconected because "connect: [Errno 111] Connection refused"

```
How to solve the problem?

**Comment by ErDmKo** [comment]
@msean It looks like you do not have the memcached server on localhost and port 11211
To solve this issue please  install it (memcached server) on your OS or use another address to connect remote server
